In [1]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import json
import matplotlib.pyplot as plt # we only need pyplot

In [2]:
data = pd.read_csv('card_data.csv')
data.head()

,Unnamed: 0,id,name,type,frameType,desc,race,archetype,card_sets,card_images,...,atk,def,level,attribute,pend_desc,monster_desc,scale,linkval,linkmarkers,banlist_info
0,0,34541863,"""A"" Cell Breeding Device",Spell Card,spell,"During each of your Standby Phases, put 1 A-Co...",Continuous,Alien,"[{'set_name': 'Force of the Breaker', 'set_cod...","[{'id': 34541863, 'image_url': 'https://images...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,64163367,"""A"" Cell Incubator",Spell Card,spell,Each time an A-Counter(s) is removed from play...,Continuous,Alien,"[{'set_name': ""Gladiator's Assault"", 'set_code...","[{'id': 64163367, 'image_url': 'https://images...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,91231901,"""A"" Cell Recombination Device",Spell Card,spell,Target 1 face-up monster on the field; send 1 ...,Quick-Play,Alien,"[{'set_name': 'Invasion: Vengeance', 'set_code...","[{'id': 91231901, 'image_url': 'https://images...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,73262676,"""A"" Cell Scatter Burst",Spell Card,spell,"Select 1 face-up ""Alien"" monster you control. ...",Quick-Play,Alien,"[{'set_name': 'Strike of Neos', 'set_code': 'S...","[{'id': 73262676, 'image_url': 'https://images...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,98319530,"""Infernoble Arms - Almace""",Spell Card,spell,While this card is equipped to a monster: You ...,Equip,Noble Knight,"[{'set_name': 'Duelist Nexus', 'set_code': 'DU...","[{'id': 98319530, 'image_url': 'https://images...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(data.dtypes)

Unnamed: 0        int64
id                int64
name             object
type             object
frameType        object
desc             object
race             object
archetype        object
card_sets        object
card_images      object
card_prices      object
atk             float64
def             float64
level           float64
attribute        object
pend_desc        object
monster_desc     object
scale           float64
linkval         float64
linkmarkers      object
banlist_info     object
dtype: object

In [4]:
data = data.drop(['desc', 'pend_desc', 'monster_desc'], axis=1)
data.head()

,Unnamed: 0,id,name,type,frameType,race,archetype,card_sets,card_images,card_prices,atk,def,level,attribute,scale,linkval,linkmarkers,banlist_info
0,0,34541863,"""A"" Cell Breeding Device",Spell Card,spell,Continuous,Alien,"[{'set_name': 'Force of the Breaker', 'set_cod...","[{'id': 34541863, 'image_url': 'https://images...","[{'cardmarket_price': '0.10', 'tcgplayer_price...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,64163367,"""A"" Cell Incubator",Spell Card,spell,Continuous,Alien,"[{'set_name': ""Gladiator's Assault"", 'set_code...","[{'id': 64163367, 'image_url': 'https://images...","[{'cardmarket_price': '0.07', 'tcgplayer_price...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,91231901,"""A"" Cell Recombination Device",Spell Card,spell,Quick-Play,Alien,"[{'set_name': 'Invasion: Vengeance', 'set_code...","[{'id': 91231901, 'image_url': 'https://images...","[{'cardmarket_price': '0.10', 'tcgplayer_price...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,73262676,"""A"" Cell Scatter Burst",Spell Card,spell,Quick-Play,Alien,"[{'set_name': 'Strike of Neos', 'set_code': 'S...","[{'id': 73262676, 'image_url': 'https://images...","[{'cardmarket_price': '0.12', 'tcgplayer_price...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,98319530,"""Infernoble Arms - Almace""",Spell Card,spell,Equip,Noble Knight,"[{'set_name': 'Duelist Nexus', 'set_code': 'DU...","[{'id': 98319530, 'image_url': 'https://images...","[{'cardmarket_price': '0.00', 'tcgplayer_price...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data['card_prices'] = data['card_prices'].str.strip('[]')
# Convert the string in the 'card_prices' column to a dictionary
data['card_prices'] = data['card_prices'].apply(lambda x: json.loads(x.replace("'", '"')))

# Normalize the 'card_prices' column to create separate columns for each key in the dictionary
data = pd.concat([data, pd.json_normalize(data['card_prices'])], axis=1)

# Now the DataFrame 'df' contains 5 new columns with the prices from the 'card_prices' column
data.head()

,Unnamed: 0,id,name,type,frameType,race,archetype,card_sets,card_images,card_prices,...,attribute,scale,linkval,linkmarkers,banlist_info,cardmarket_price,tcgplayer_price,ebay_price,amazon_price,coolstuffinc_price
0,0,34541863,"""A"" Cell Breeding Device",Spell Card,spell,Continuous,Alien,"[{'set_name': 'Force of the Breaker', 'set_cod...","[{'id': 34541863, 'image_url': 'https://images...","{'cardmarket_price': '0.10', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,NaN,0.10,0.19,0.99,24.45,0.25
1,1,64163367,"""A"" Cell Incubator",Spell Card,spell,Continuous,Alien,"[{'set_name': ""Gladiator's Assault"", 'set_code...","[{'id': 64163367, 'image_url': 'https://images...","{'cardmarket_price': '0.07', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,NaN,0.07,0.24,1.25,0.50,0.25
2,2,91231901,"""A"" Cell Recombination Device",Spell Card,spell,Quick-Play,Alien,"[{'set_name': 'Invasion: Vengeance', 'set_code...","[{'id': 91231901, 'image_url': 'https://images...","{'cardmarket_price': '0.10', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,NaN,0.10,0.20,0.99,0.50,0.49
3,3,73262676,"""A"" Cell Scatter Burst",Spell Card,spell,Quick-Play,Alien,"[{'set_name': 'Strike of Neos', 'set_code': 'S...","[{'id': 73262676, 'image_url': 'https://images...","{'cardmarket_price': '0.12', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,NaN,0.12,0.10,2.00,9.76,0.25
4,4,98319530,"""Infernoble Arms - Almace""",Spell Card,spell,Equip,Noble Knight,"[{'set_name': 'Duelist Nexus', 'set_code': 'DU...","[{'id': 98319530, 'image_url': 'https://images...","{'cardmarket_price': '0.00', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,NaN,0.00,0.64,0.00,0.00,0.00

In [11]:
unique_types = data['type'].unique()
print(unique_types)

['Spell Card' 'Effect Monster' 'Normal Monster' 'Flip Effect Monster'
 'Trap Card' 'Union Effect Monster' 'Fusion Monster'
 'Pendulum Effect Monster' 'Link Monster' 'XYZ Monster' 'Synchro Monster'
 'Synchro Tuner Monster' 'Tuner Monster' 'Gemini Monster'
 'Normal Tuner Monster' 'Spirit Monster' 'Ritual Effect Monster'
 'Skill Card' 'Token' 'Pendulum Effect Fusion Monster' 'Ritual Monster'
 'Toon Monster' 'Pendulum Normal Monster'
 'Synchro Pendulum Effect Monster' 'Pendulum Tuner Effect Monster'
 'XYZ Pendulum Effect Monster' 'Pendulum Effect Ritual Monster'
 'Pendulum Flip Effect Monster']

In [13]:
data = data[~data['type'].isin(['Spell Card', 'Trap Card', 'Token'])]
data.head()

,Unnamed: 0,id,name,type,frameType,race,archetype,card_sets,card_images,card_prices,...,attribute,scale,linkval,linkmarkers,banlist_info,cardmarket_price,tcgplayer_price,ebay_price,amazon_price,coolstuffinc_price
10,10,86988864,3-Hump Lacooda,Effect Monster,effect,Beast,NaN,"[{'set_name': 'Ancient Sanctuary', 'set_code':...","[{'id': 86988864, 'image_url': 'https://images...","{'cardmarket_price': '0.16', 'tcgplayer_price'...",...,EARTH,NaN,NaN,NaN,NaN,0.16,0.16,1.00,0.25,0.25
11,11,11714098,"30,000-Year White Turtle",Normal Monster,normal,Aqua,NaN,NaN,"[{'id': 11714098, 'image_url': 'https://images...","{'cardmarket_price': '0.00', 'tcgplayer_price'...",...,WATER,NaN,NaN,NaN,NaN,0.00,0.00,10.00,0.50,0.00
12,12,83994646,4-Starred Ladybug of Doom,Flip Effect Monster,effect,Insect,NaN,"[{'set_name': 'Dark Beginning 1', 'set_code': ...","[{'id': 83994646, 'image_url': 'https://images...","{'cardmarket_price': '0.12', 'tcgplayer_price'...",...,WIND,NaN,NaN,NaN,NaN,0.12,0.05,0.99,0.99,0.25
14,14,23771716,7 Colored Fish,Normal Monster,normal,Fish,NaN,"[{'set_name': 'Gold Series', 'set_code': 'GLD1...","[{'id': 23771716, 'image_url': 'https://images...","{'cardmarket_price': '0.06', 'tcgplayer_price'...",...,WATER,NaN,NaN,NaN,NaN,0.06,0.16,1.99,2.77,0.39
16,16,14261867,8-Claws Scorpion,Effect Monster,effect,Insect,NaN,"[{'set_name': 'Gold Series', 'set_code': 'GLD1...","[{'id': 14261867, 'image_url': 'https://images...","{'cardmarket_price': '0.11', 'tcgplayer_price'...",...,DARK,NaN,NaN,NaN,NaN,0.11,0.22,0.99,0.20,0.25

In [15]:
# Define the bins for the level ranges
bins = [1.0, 4.0, 6.0, float('inf')]

# Define the labels for the level ranges
labels = ['0', '1', '2']

# Create a new column 'level_group' to store the bucketed groups
data['tribute'] = pd.cut(data['level'], bins=bins, labels=labels, right=False)

# Now the DataFrame 'df' contains a new column 'level_group' with the cards bucketed into the specified level ranges
data.head()

,Unnamed: 0,id,name,type,frameType,race,archetype,card_sets,card_images,card_prices,...,scale,linkval,linkmarkers,banlist_info,cardmarket_price,tcgplayer_price,ebay_price,amazon_price,coolstuffinc_price,tribute
10,10,86988864,3-Hump Lacooda,Effect Monster,effect,Beast,NaN,"[{'set_name': 'Ancient Sanctuary', 'set_code':...","[{'id': 86988864, 'image_url': 'https://images...","{'cardmarket_price': '0.16', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,0.16,0.16,1.00,0.25,0.25,0
11,11,11714098,"30,000-Year White Turtle",Normal Monster,normal,Aqua,NaN,NaN,"[{'id': 11714098, 'image_url': 'https://images...","{'cardmarket_price': '0.00', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,0.00,0.00,10.00,0.50,0.00,1
12,12,83994646,4-Starred Ladybug of Doom,Flip Effect Monster,effect,Insect,NaN,"[{'set_name': 'Dark Beginning 1', 'set_code': ...","[{'id': 83994646, 'image_url': 'https://images...","{'cardmarket_price': '0.12', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,0.12,0.05,0.99,0.99,0.25,0
14,14,23771716,7 Colored Fish,Normal Monster,normal,Fish,NaN,"[{'set_name': 'Gold Series', 'set_code': 'GLD1...","[{'id': 23771716, 'image_url': 'https://images...","{'cardmarket_price': '0.06', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,0.06,0.16,1.99,2.77,0.39,1
16,16,14261867,8-Claws Scorpion,Effect Monster,effect,Insect,NaN,"[{'set_name': 'Gold Series', 'set_code': 'GLD1...","[{'id': 14261867, 'image_url': 'https://images...","{'cardmarket_price': '0.11', 'tcgplayer_price'...",...,NaN,NaN,NaN,NaN,0.11,0.22,0.99,0.20,0.25,0